### ISSUE TITLE
How to deal with space in path when execute command in windows?

### ISSUE THREAD

**Issue by catfishlty** [commander-cli/cmd#19]
### Ex.1
```go
c := cmd.NewCommand(`"C:\Program Files\Java\jre1.8.0_192\bin\java.exe" --version`)
    _ = c.Execute()
    fmt.Println(c.Stdout())
    fmt.Println(c.Stderr())
```
```cmd
'\"C:\Program Files\Java\jre1.8.0_192\bin\java.exe\"' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

Plz focus on the path string. And I don't know why `\"` instead of `"`

### Ex.2
```go
c := cmd.NewCommand(`C:\Program Files\Java\jre1.8.0_192\bin\java.exe --version`)
    _ = c.Execute()
    fmt.Println(c.Stdout())
    fmt.Println(c.Stderr())
```

```cmd
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

**Ex.1 and Ex.2 can solve by define the `workingDir`**

### Ex.3
When some problem need an arguments with a windows style file with space, the error occurs.
And I didn't find the way to solve it.

**Plz help~**

**Comment by dylanhitt** [comment]
@catfishlty I wonder if this could be easily handled with the stdlib path package https://pkg.go.dev/path?

**Comment by dylanhitt** [comment]
Closing feel free to comment if you're still having this issue. I haven't been able to reproduce.

**Comment by catfishlty** [comment]
Thanks for your reply, I'll try it.
