### ISSUE TITLE
Run as a specified user

### ISSUE THREAD

**Issue by wahello** [commander-cli/cmd#34]
### How to run command as specified user?

**Comment by dylanhitt** [comment]
Hey @wahello 👋 

Thank you for the issue. There currently isn't a direct to do this. However I believe it can be accomplished with [`WithCustomBasedCommand`](https://pkg.go.dev/github.com/commander-cli/cmd#WithCustomBaseCommand)

Something like 

```golang
rawcmd := exec.Command(command, args...)
rawcmd.SysProcAttr = &syscall.SysProcAttr{}
rawcmd.SysProcAttr.Credential = &syscall.Credential{Uid: uid, Gid: gid}

cmd := NewCommand(
		"echo $0",
		WithCustomBaseCommand(rawcmd),
)
```

That should get you past your current issue.

That being said `WithUser` would be a pretty great option. I'll be adding that on a rainy day 

Cheers

**Comment by dylanhitt** [comment]
@wahello let me know if #35 is what you're looking for.
